### ISSUE TITLE
Wrong log filename printed

### ISSUE THREAD

**Issue by XiaominZhang** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#49]
When a query is failed in throughput phase, the BB driver prints below message:

Benchmark run terminated
Reason: An error occured while running a command
==============
java.io.IOException: Error while running query 23. More information in logfile: 
/root/Big-Data-Benchmark-for-Big-Bench/logs/q23_throughput_test_1_1.log
	at io.bigdatabenchmark.v1.driver.BigBench$QueryThread.call(BigBench.java:1272)
	at io.bigdatabenchmark.v1.driver.BigBench$QueryThread.call(BigBench.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745) java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at io.bigdatabenchmark.v1.driver.BigBench.runCmd(BigBench.java:538)
	at io.bigdatabenchmark.v1.driver.BigBench.access$4(BigBench.java:511)
	at io.bigdatabenchmark.v1.driver.BigBench$QueryThread.call(BigBench.java:1266)
	at io.bigdatabenchmark.v1.driver.BigBench$QueryThread.call(BigBench.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

However, the correct log file name should be /root/Big-Data-Benchmark-for-Big-Bench/logs/q23_hive_throughput_test_1_1.log

**Comment by Manuel-Danisch** [comment]
Hi @XiaominZhang,

Fixed in 9ae72ec5db5ed6f7c3764b8913af4713a53109cf. Thanks for the report.

Best regards,

Manuel
