### ISSUE TITLE
Failed to run BigBench on Spark engine (SparkSQL)

### ISSUE THREAD

**Issue by liujun1105** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#61]
Below is the error I get.

BigBench benchmark: Start
BigBench phase 2: Power test                            Running queries on          1 stream(s)
BigBench phase 2: Power test                            stream          0, query  2 ( 1/ 1) log file: /home/chenwenwen/Big-Data-Benchmark-for-Big-Bench/logs/q02_spark_power_test_0.log
==============
Benchmark run terminated
Reason: An error occured while running a command
==============
java.io.IOException: Error while running query 2. More information in logfile: /home/chenwenwen/Big-Data-Benchmark-for-Big-Bench/logs/q02_spark_power_test_0.log
	at io.bigdatabenchmark.v1.driver.BigBench$QueryThread.call(BigBench.java:1285)
	at io.bigdatabenchmark.v1.driver.BigBench$QueryThread.call(BigBench.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Here's what I found in the log
python: can't open file 'q2-sessionize.py': [Errno 2] No such file or directory

The file q2-sessionize.py, it is probably to do with the sql statement not specifying the path of the q2-sessionize.py

**Comment by Michael-Frank** [comment]
new release version [1.0](https://github.com/intel-hadoop/Big-Data-Benchmark-for-Big-Bench/releases/tag/1.0) received an overhaul. this issue should no longer apply.
