### ISSUE TITLE
NoSuchTableException: q05 Step 2/3: logistic regression failure

### ISSUE THREAD

**Issue by nakhanha** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#76]
**spark-submit --class io.bigdatabenchmark.v1.queries.q05.LogisticRegression /home/nakhanha/Big-Data-Benchmark-for-Big-Bench/engines/hive/queries/Resources/bigbench-ml-spark.jar --fromHiveMetastore true -i bigbench.q05_hive_engine_validation_power_test_0_temp -o /user/nakhanha/benchmarks/bigbench/queryResults/q05_hive_engine_validation_power_test_0_result// --type LBFGS --step-size 1 --iterations 20 --lambda 0 --numClasses 2 --convergenceTol 1e-5 --numCorrections 10 --saveClassificationResult false --saveMetaInfo true --verbose false**

SPARK_MAJOR_VERSION is set to 1, using Spark
Run LogisticRegression with options: Map('csvInputDelimiter -> ,, 'fromHiveMetastore -> true, 'verbose -> false, 'saveMetaInfo -> true, 'lambda -> 0, 'numCorrections -> 10, 'stepsize -> 1, 'convergenceTol -> 1e-5, 'iter -> 20, 'output -> /user/nakhanha/benchmarks/bigbench/queryResults/q05_hive_engine_validation_power_test_0_result//, 'type -> LBFGS, 'saveClassificationResult -> false, 'input -> bigbench.q05_hive_engine_validation_power_test_0_temp, 'numClasses -> 2)
18/06/06 22:34:47 INFO slf4j.Slf4jLogger: Slf4jLogger started
18/06/06 22:34:47 INFO Remoting: Starting remoting
18/06/06 22:34:47 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@10.0.0.21:29865]
loading data from metastore table: "bigbench.q05_hive_engine_validation_power_test_0_temp" ...
18/06/06 22:34:49 INFO DataNucleus.Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
18/06/06 22:34:49 INFO DataNucleus.Persistence: Property datanucleus.cache.level2 unknown - will be ignored
18/06/06 22:34:49 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/06 22:34:49 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/06 22:34:56 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:34:56 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:02 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:02 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:04 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:06 INFO DataNucleus.Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
18/06/06 22:35:06 INFO DataNucleus.Persistence: Property datanucleus.cache.level2 unknown - will be ignored
18/06/06 22:35:06 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/06 22:35:06 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:08 INFO DataNucleus.Query: Reading in results for query "org.datanucleus.store.rdbms.query.SQLQuery@0" since the connection used is closing
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
**Exception in thread "main" org.apache.spark.sql.catalyst.analysis.NoSuchTableException**
        at org.apache.spark.sql.hive.client.ClientInterface$$anonfun$getTable$1.apply(ClientInterface.scala:122)
        at org.apache.spark.sql.hive.client.ClientInterface$$anonfun$getTable$1.apply(ClientInterface.scala:122)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.sql.hive.client.ClientInterface$class.getTable(ClientInterface.scala:122)
        at org.apache.spark.sql.hive.client.ClientWrapper.getTable(ClientWrapper.scala:61)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog.lookupRelation(HiveMetastoreCatalog.scala:414)
        at org.apache.spark.sql.hive.HiveContext$$anon$2.org$apache$spark$sql$catalyst$analysis$OverrideCatalog$$super$lookupRelation(HiveContext.scala:475)
        at org.apache.spark.sql.catalyst.analysis.OverrideCatalog$class.lookupRelation(Catalog.scala:162)
        at org.apache.spark.sql.hive.HiveContext$$anon$2.lookupRelation(HiveContext.scala:475)
        at org.apache.spark.sql.SQLContext.table(SQLContext.scala:831)
        at org.apache.spark.sql.SQLContext.table(SQLContext.scala:827)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression$.loadfromHiveMetastore(LogisticRegression.scala:188)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression$.main(LogisticRegression.scala:99)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression.main(LogisticRegression.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:750)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/06/06 22:35:09 INFO remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
18/06/06 22:35:09 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
18/06/06 22:35:09 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
nakhanha@hn0-hdil4:~/Big-Data-Benchmark-for-Big-Bench/bin$

Is there something I am missing. because I checked in hive cli for tables and table exist. Please let me know.

hive> use bigbench;
OK
Time taken: 0.054 seconds
hive> show tables;
OK
customer
customer_address
customer_demographics
date_dim
household_demographics
income_band
inventory
item
item_marketprices
product_reviews
promotion
q01_hive_engine_validation_power_test_0_result
q02_hive_engine_validation_power_test_0_result
q03_hive_engine_validation_power_test_0_result
q04_hive_engine_validation_power_test_0_result
**q05_hive_engine_validation_power_test_0_temp**
reason
ship_mode
store
store_returns
store_sales
time_dim
warehouse
web_clickstreams
web_page
web_returns
web_sales
web_site
Time taken: 0.123 seconds, Fetched: 28 row(s)
hive>

**Comment by carabolic** [comment]
Hi @nakhanha ,

this line made me suspicious

```
"org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
```

can you verify that you Spark installation is configured properly to connect to the Hive metastore?

Usually this is done by copying the `hive-site.xml` into `$SPARK_HOME/conf/` .

If everything is setup properly you can open the `spark-shell` and connect to the Hive metastore:

```scala
scala> val res = sqlContext.sql("SELECT c_first_name FROM bigbench.customer LIMIT 10")
res: org.apache.spark.sql.DataFrame = [c_first_name: string]

scala> res.show()
+------------+
|c_first_name|
+------------+
|     Jasmine|
|        Lula|
|      Shayna|
|       Jason|
|        Ruth|
|      Benito|
|       Isaac|
|     Kathryn|
|     Jeffery|
|      Thelma|
+------------+


scala>
```

Please let me know how it went.

**Comment by nakhanha** [comment]
Thanks for you reply @carabolic . Can you please tell If I am supposed to copy hive-site.xml under hive-client to $SPARK_HOME/conf ?

because I copied  sudo cp /usr/hdp/current/hive-client/conf/hive-site.xml /usr/hdp/current/spark-client/conf/ 

spark-submit --class io.bigdatabenchmark.v1.queries.q05.LogisticRegression /home/nakhanha/Big-Data-Benchmark-for-Big-Bench/engines/hive/queries/Resources/bigbench-ml-spark.jar --fromHiveMetastore true -i bigbench.q05_hive_engine_validation_power_test_0_temp -o /user/nakhanha/benchmarks/bigbench/queryResults/q05_hive_engine_validation_power_test_0_result// --type LBFGS --step-size 1 --iterations 20 --lambda 0 --numClasses 2 --convergenceTol 1e-5 --numCorrections 10 --saveClassificationResult false --saveMetaInfo true --verbose false
SPARK_MAJOR_VERSION is set to 1, using Spark
Run LogisticRegression with options: Map('csvInputDelimiter -> ,, 'fromHiveMetastore -> true, 'verbose -> false, 'saveMetaInfo -> true, 'lambda -> 0, 'numCorrections -> 10, 'stepsize -> 1, 'convergenceTol -> 1e-5, 'iter -> 20, 'output -> /user/nakhanha/benchmarks/bigbench/queryResults/q05_hive_engine_validation_power_test_0_result//, 'type -> LBFGS, 'saveClassificationResult -> false, 'input -> bigbench.q05_hive_engine_validation_power_test_0_temp, 'numClasses -> 2)
18/06/07 17:52:54 INFO slf4j.Slf4jLogger: Slf4jLogger started
18/06/07 17:52:54 INFO Remoting: Starting remoting
18/06/07 17:52:55 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@10.0.0.21:30163]
loading data from metastore table: "bigbench.q05_hive_engine_validation_power_test_0_temp" ...
18/06/07 17:52:56 INFO DataNucleus.Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
18/06/07 17:52:56 INFO DataNucleus.Persistence: Property datanucleus.cache.level2 unknown - will be ignored
18/06/07 17:52:57 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/07 17:52:57 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/07 17:53:04 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/07 17:53:04 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/07 17:53:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/07 17:53:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/07 17:53:10 WARN metadata.Hive: Failed to access metastore. This class should not accessed in runtime.
org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
        at org.apache.hadoop.hive.ql.metadata.Hive.getAllDatabases(Hive.java:1236)
        at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:174)
        at org.apache.hadoop.hive.ql.metadata.Hive.<clinit>(Hive.java:166)
        at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
        at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:209)
        at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:238)
        at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:225)
        at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:215)
        at org.apache.spark.sql.hive.HiveContext.functionRegistry$lzycompute(HiveContext.scala:480)
        at org.apache.spark.sql.hive.HiveContext.functionRegistry(HiveContext.scala:479)
        at org.apache.spark.sql.UDFRegistration.<init>(UDFRegistration.scala:40)
        at org.apache.spark.sql.SQLContext.<init>(SQLContext.scala:330)
        at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:90)
        at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:101)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression$.loadfromHiveMetastore(LogisticRegression.scala:187)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression$.main(LogisticRegression.scala:99)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression.main(LogisticRegression.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:750)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1523)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
        at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
        at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
        at org.apache.hadoop.hive.ql.metadata.Hive.getAllDatabases(Hive.java:1234)
        ... 25 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)
        ... 31 more
Caused by: MetaException(message:Version information not found in metastore. )
        at org.apache.hadoop.hive.metastore.ObjectStore.checkSchema(ObjectStore.java:6664)
        at org.apache.hadoop.hive.metastore.ObjectStore.verifySchema(ObjectStore.java:6645)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:114)
        at com.sun.proxy.$Proxy17.verifySchema(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:572)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultDB(HiveMetaStore.java:620)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:461)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:66)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:72)
        at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:5762)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:199)
        at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)
        ... 36 more
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
        at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
        at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:209)
        at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:238)
        at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:225)
        at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:215)
        at org.apache.spark.sql.hive.HiveContext.functionRegistry$lzycompute(HiveContext.scala:480)
        at org.apache.spark.sql.hive.HiveContext.functionRegistry(HiveContext.scala:479)
        at org.apache.spark.sql.UDFRegistration.<init>(UDFRegistration.scala:40)
        at org.apache.spark.sql.SQLContext.<init>(SQLContext.scala:330)
        at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:90)
        at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:101)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression$.loadfromHiveMetastore(LogisticRegression.scala:187)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression$.main(LogisticRegression.scala:99)
        at io.bigdatabenchmark.v1.queries.q05.LogisticRegression.main(LogisticRegression.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:750)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1523)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
        at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
        at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
        at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
        ... 22 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)
        ... 28 more
Caused by: MetaException(message:Version information not found in metastore. )
        at org.apache.hadoop.hive.metastore.ObjectStore.checkSchema(ObjectStore.java:6664)
        at org.apache.hadoop.hive.metastore.ObjectStore.verifySchema(ObjectStore.java:6645)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:114)
        at com.sun.proxy.$Proxy17.verifySchema(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:572)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultDB(HiveMetaStore.java:620)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:461)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:66)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:72)
        at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:5762)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:199)
        at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)
        ... 33 more
18/06/07 17:53:10 INFO remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
18/06/07 17:53:10 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
nakhanha@hn0-hdil4:~/Big-Data-Benchmark-for-Big-Bench$

**Comment by nakhanha** [comment]
HI @carabolic ,

Thank you so much for your reply and help.

The method worked. 
https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.4/bk_spark-component-guide/content/spark-config-hive.html

**Comment by carabolic** [comment]
Good to hear that you were successful.
